use_frameworks!

target 'AISocket_Example' do
    pod 'AISocket', :path => '../'
    pod 'Realm'
    pod 'KVOController'
    #pod 'JSQMessagesViewController'

  target 'AISocket_Tests' do
    inherit! :search_paths
    pod 'Realm/Headers'

    
  end
end
